CATALOGUE_HOST: catalogue.roboshopdaws84.site
USER_HOST: user.roboshopdaws84.site
CART_HOST: cart.roboshopdaws84.site
SHIPPING_HOST: shipping.roboshopdaws84.site
PAYMENT_HOST: payment.roboshopdaws84.site