[mongodb]
mongodb.roboshopdaws84.site
[catalogue]
catalogue.roboshopdaws84.site
[redis]
redis.roboshopdaws84.site
[cart]
cart.roboshopdaws84.site
[user]
user.roboshopdaws84.site
[frontend]
frontend.roboshopdaws84.site
[mysql]
mysql.roboshopdaws84.site
[shipping]
shipping.roboshopdaws84.site
[rabbitmq]
rabbitmq.roboshopdaws84.site
[payment]
payment.roboshopdaws84.site


[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321

