- name: Installing python3 packages
  ansible.builtin.pip:
    name: "{{item}}"
    state: installed
  loop:
  - python3 
  - gcc 
  - python3-devel

- name: create roboshop system payment
  ansible.builtin.user:
    name: roboshop
    shell: /sbin/nologin
    system: true
    home: /app

- name: create app directory 
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download the payment code 
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/payment-v3.zip
    dest: /tmp/payment.zip

- name: extract cataloge code 
  ansible.builtin.unarchive:
    src: /tmp/payment.zip
    dest: /app
    remote_src: yes

- name: Install dependencies
  ansible.builtin.pip:
    requirements: requirements.txt
    executable: pip3.9  
  args:
    chdir: /app

- name: copy payment service to system directory 
  ansible.builtin.copy:
    src: payment.service
    dest: /etc/systemd/system/payment.service

- name: systemctl demon reload
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: start and enable payment
  ansible.builtin.service:
    name: payment 
    state: started
    enabled: yes

  