# - name: Installing python3 packages
#   ansible.builtin.pip:
#     name: "{{ item }}"
#     state: installed
#   loop:
#   - python3
#   - gcc 
#   - python3-devel

- name: Install system packages
  ansible.builtin.yum:
    name:
      - python3
      - gcc
      - python3-devel
    state: present
    
- name: Install dependencies
  ansible.builtin.pip:
    requirements: requirements.txt
    executable: pip3.9  
  args:
    chdir: /app